/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import com.alexshegstad.footballsimulator.App; // Add this import

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App(); // Now this will work
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
